language: node_js
node_js:
- node
cache:
  directories:
  - node_modules
script:
- npm run production
before_deploy:
- openssl aes-256-cbc -K $encrypted_143f87a44a6a_key -iv $encrypted_143f87a44a6a_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
addons:
  ssh_known_hosts: uiengine-sample-react.uix.space
deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master
