name: Node CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12]

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install
      run: npm ci
    - name: Build
      run: |
        npm run production
        # GitHub Pages SPA
        cp deploy/404.html out/404.html
        cp deploy/gh-pages-spa.js out/gh-pages-spa.js
        sed '7i\'$'\n''<script src="/gh-pages-spa.js"></script>'$'\n' out/design-system/index.html > out/design-system/index-modified.html
        mv out/design-system/index{-modified,}.html
        # https://github.blog/2009-12-29-bypassing-jekyll-on-github-pages/
        touch out/.nojekyll
        # https://help.github.com/en/articles/managing-a-custom-domain-for-your-github-pages-site
        echo uiengine-sample-react.uix.space > out/CNAME
      env:
        CI: true
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        BUILD_DIR: out/
        GH_PAT: ${{ secrets.GH_PAT }}
